### PR TITLE
Make things work for Linux

### PR DESCRIPTION
**Pull request by hartwork**
Hi @BenPyton,

for the moment this includes, in separate commits:
- a simple build system based on CMake >=3.6,
- small C/C++ fixes to get the code to compile,
- a fix for name derivation of audio devices so the microphone has a chance to work,
- a simple GitHub Actions CI to build with recent GCC 11/12 and Clang 15/16/17 (can be seen already at https://github.com/hartwork/OsciView/actions),
- plus a simple GitHub Dependbot config to make it help out with pull request like https://github.com/uriparser/uriparser/pull/159 in the future, the part that likely sounds least interesting right now.

The good news is that it compiles and runs and animates audio input :tada: 
The bad news is that the fragment shader embedded at…

https://github.com/BenPyton/OsciView/blob/88f6da3ff07608b6d7948bfae1d9742b265d2219/src/OsciView.cpp#L19-L74

gets me runtime error…
```
Failed to compile fragment shader:
0:27(7): error: syntax error, unexpected NEW_IDENTIFIER, expecting ',' or ';'

Error while loading fragment shader
```
…because seemingly of e.g. use of `uint` and `round`. Based on a warning I got while playing with it, I believe it wants GLSL 1.10 input but it get's something else — I have no background on shaders.

What do you think?

Best, Sebastian

### CODE REVIEW

**Comment by BenPyton** [comment]
I'll take a look at it when I have some more free time for the various fixes you've done :)

**Comment by hartwork** [comment]
@BenPyton sure! I advise review on a commit-by-commit basis at https://github.com/BenPyton/OsciView/pull/2/commits rather than the combined diff. The commits tell a story and were meant to explain themselves in isolation. See you :wave:

**Comment by BenPyton** [comment]
First of, for your shader issue, it seems your compiler doesn't recognize uint...

I've added those 2 lines in the `main()`, right after the `Window::Create(...)` to get what OpenGL version is used:
```cpp
	sf::ContextSettings settings = Window::GetWindow()->getSettings();
	std::cout << "OpenGL version:"<< settings.majorVersion << "." << settings.minorVersion << std::endl;
```

My version of OpenGL is 4.6, and so GLSL is 4.6.
Can you tell me what version of OpenGL you have, please?

I've tested some version requirements in the shader and the minimum version where it works is OpenGL 3.3.
Could you try adding this line right after the `//FRAGMENT SHADER` comment?
```cpp
\n	#version 330\
```

**Comment by BenPyton** [comment]
Ok, I've reviewed the commits, here my comments:
- d95520b: the `#ifdef WIN32` should be replaced by `#ifdef _WIN32`
- 1cce878: This adds more incoherences in the defines... I missed several files with define `XXX_H_INCLUDED` when I changed them... 
I think we should change the standard and create somethin like `CORE_XXX_H` for files in `Core` folder, `UI_XXX_H` in the UI folder, etc. and `OSCIVIEW_XXX_H` in the main `src` folder.
I had planned to create a separate lib in its own github repo for the `Core`, `UI` and `Math` folders.
- 3ac3382: I see you've set up a cron job to build on a weekly basis, is it doing it even if no new commits? If yes, I think it should be better to do on each push or pull request because there are not enough commits done at this frequency.
- 5acb9fe: I would like to build on Windows too with cmake, do you know if it's better to install pkg-config or if I should make platform checks? I would like later to remove the Visual Studio project to instead use cmake on all platform.

**Comment by hartwork** [comment]
@BenPyton great input, let me have a closer look, I think I'll have a full reply in maybe 30 minutes.

**Comment by hartwork** [comment]
> First of, for your shader issue, it seems your compiler doesn't recognize uint...

@BenPyton yes!

> I've added those 2 lines in the `main()`, right after the `Window::Create(...)` to get what OpenGL version is used:
> 
> ```c++
> 	sf::ContextSettings settings = Window::GetWindow()->getSettings();
> 	std::cout << "OpenGL version:"<< settings.majorVersion << "." << settings.minorVersion << std::endl;
> ```
> 
> My version of OpenGL is 4.6, and so GLSL is 4.6. Can you tell me what version of OpenGL you have, please?

Did that now, says `OpenGL version:3.3`. Hardware is an i5 Lenovo ThinkPad X220 with an Intel graphics card from ~10 years ago.

> I've tested some version requirements in the shader and the minimum version where it works is OpenGL 3.3. Could you try adding this line right after the `//FRAGMENT SHADER` comment?
> 
> ```c++
> \n	#version 330\
> ```

Interesting, it changed the output to this:
```
Failed to compile fragment shader:
0:37(26): error: `gl_Color' undeclared
0:37(14): error: no matching function for call to `decodeFloat(error)'; candidates are:
0:37(14): error:    float decodeFloat(vec4)
0:38(12): error: `gl_TexCoord' undeclared
0:38(12): error: type mismatch
0:42(5): warning: `len' used uninitialized
0:45(26): warning: `xy' used uninitialized
0:50(14): warning: `xy' used uninitialized
0:50(56): warning: `xy' used uninitialized
0:50(63): warning: `len' used uninitialized
0:51(16): warning: `xy' used uninitialized
0:51(23): warning: `xy' used uninitialized
0:51(61): warning: `len' used uninitialized
```

> Ok, I've reviewed the commits, here my comments:

Thanks!


> * [d95520b](https://github.com/BenPyton/OsciView/commit/d95520bc46d202ac7fc0b4ee1a163679de40dfab): the `#ifdef WIN32` should be replaced by `#ifdef _WIN32`

Sure, done.

> * [1cce878](https://github.com/BenPyton/OsciView/commit/1cce878fd08f3ab548ba8cb6925b8d2161b4c215): This adds more incoherences in the defines... I missed several files with define `XXX_H_INCLUDED` when I changed them...
>       I think we should change the standard and create somethin like `CORE_XXX_H` for files in `Core` folder, `UI_XXX_H` in the UI folder, etc. and `OSCIVIEW_XXX_H` in the main `src` folder.
>       I had planned to create a separate lib in its own github repo for the `Core`, `UI` and `Math` folders.

My key concern was fixing compilation. I'm happy to adjust as you like if it's simple inside the pull request. Else I would suggest we decouple the fix and the improvment and make a second pull request. How would you like to continue here?

> * [3ac3382](https://github.com/BenPyton/OsciView/commit/3ac3382aebe71e1b617763097cfbfca8fc9f0862): I see you've set up a cron job to build on a weekly basis, is it doing it even if no new commits? If yes, I think it should be better to do on each push or pull request because there are not enough commits done at this frequency.

Let me explain the idea behind it. For a robust CI the ground should not be moving so that the CI only ever fails when our code started doing something wrong. In reality, the ground is moving all the time and so if we don't compile things for month when there are no commits we won't noticed the the ground below us shifted and is cause the breakage. We'd only find out way later when some opens a pull request and then that will stand in the way of their contribution. So the idea is to complete once per week even without any new commits happening, that's the idea. I'm doing that in all my projects where I was aware of the problem at the time of adding CI. What do you think?

> * [5acb9fe](https://github.com/BenPyton/OsciView/commit/5acb9fe72d026c92492f52ed7c30b7dd2b4750fb): I would like to build on Windows too with cmake

Good idea!

>, do you know if it's better to install pkg-config or if I should make platform checks?

I think what you're saying is that pkg-config is not commonly available on Windows and then the question is whether to still use it or what to use instead? With only SFML for a dependency here which comes with CMake files to help CMake find it even without pkg-config, we can go the CMake native way using `find_package` instead. These are the files I have in mind:
```console
# qlist media-libs/libsfml | grep cmake
/usr/lib64/cmake/SFML/SFMLSharedTargets.cmake
/usr/lib64/cmake/SFML/SFMLSharedTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SFML/SFMLConfig.cmake
/usr/lib64/cmake/SFML/SFMLConfigDependencies.cmake
/usr/lib64/cmake/SFML/SFMLConfigVersion.cmake
/usr/share/cmake/Modules/SFMLConfig.cmake.in
/usr/share/cmake/Modules/SFMLConfigDependencies.cmake.in
```
Command `qlist` is specific to Gentoo Linux, imagine any "list of files of installed package for SFML" command here.
I'm wondering two things now:
- Would [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) address the converns/question you had in mind?
- Would it be important to you to use `find_package` before a merge or can we decouple that for the next iteration?

> I would like later to remove the Visual Studio project to instead use cmake on all platform.

Good idea! Did you know that CMake can [generate](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#introduction) not just Makefiles and Ninja build files but also [Visual Studio solution files](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators) up to version Visual Studio 17 2022? So users will still be able to fire up and work in MSVC if they prefer.

**Comment by BenPyton** [comment]
For the shader issues, check if shaders are available on your computer with:
```cpp
sf::Shader::isAvailable();
```
It should be yes, and if so can you try to compile a simple sfml program please?
https://www.sfml-dev.org/tutorials/2.0/graphics-shader.php

> I would suggest we decouple the fix and the improvment

Okay, I respect your suggestion and we'll do that 😄 Keep current changes and we will improve that later.

> the ground is moving all the time and so if we don't compile things for month when there are no commits we won't noticed the the ground below us shifted and is cause the breakage.

I agree with you, it is important for projects with lots of deps, but here there is only SFML as dependency and we could (should?) freeze the version it is using to compile. It seems a bit overkill to me to do dozens of builds per year for a project nobody uses...
However, if you really want to make a regular build, I suggest to do monthly instead.

> Did you know that CMake can generate [...] Visual Studio solution files

Yes I knew 😅 I meant not relying on MSVC, even for the Windows build releases.

> Would it be important to you to use `find_package` before a merge or can we decouple that for the next iteration?

We can decouple, but I would like first to compile and test on Windows with Cmake on my side before merging the PR.

**Comment by hartwork** [comment]
> For the shader issues, check if shaders are available on your computer with:
> 
> ```c++
> sf::Shader::isAvailable();
> ```

@BenPyton it says `1`, I suppose that's a yes :smile: 


> It should be yes, and if so can you try to compile a simple sfml program please? https://www.sfml-dev.org/tutorials/2.0/graphics-shader.php

I don't see a ready program there, it looks like a tutorial with pieces. I'm happy to try ready code. What question in particualr do we hope to try to answer with that, just to better understand? I have seen other shaders working on this machine before, so there is some hope.

> > I would suggest we decouple the fix and the improvment
> 
> Okay, I respect your suggestion and we'll do that smile Keep current changes and we will improve that later.

Cool! :+1: 

> > the ground is moving all the time and so if we don't compile things for month when there are no commits we won't noticed the the ground below us shifted and is cause the breakage.
> 
> I agree with you, it is important for projects with lots of deps, but here there is only SFML as dependency and we could (should?) freeze the version it is using to compile. It seems a bit overkill to me to do dozens of builds per year for a project nobody uses... However, if you really want to make a regular build, I suggest to do monthly instead.

It's not just our direct dependencies, it's also CMake and the compiler, the whole environment. Here are some examples that I needed to fix over time where the ground moved below my feet and things were working on my side before:
- https://github.com/libexpat/libexpat/pull/689
- https://github.com/libexpat/libexpat/pull/678
- https://github.com/libexpat/libexpat/pull/632

I have made it to run monthly now, please check the crontab syntax if it matches the comment and looks correct, it's just too easy to get wrong. Thanks!

> > Did you know that CMake can generate [...] Visual Studio solution files
> 
> Yes I knew sweat_smile I meant not relying on MSVC, even for the Windows build releases.

This could even work with MinGW in CI at some point I think, if you like. As in no MSVC at all.

> > Would it be important to you to use `find_package` before a merge or can we decouple that for the next iteration?
> 
> We can decouple, but I would like first to compile and test on Windows with CMake on my side before merging the PR.

Sure, take your time :+1:

**Comment by BenPyton** [comment]
@hartwork I know how to fix quickly your shader issue, add the `compatibility` keyword after the version number like this:
```
\n	#version 330 compatibility\
```
Because `gl_TexCoord` and other hard coded in/out of GLSL has been deprecated since a long time.
Later I should update the fragment shader for a more modern GLSL.

**Comment by hartwork** [comment]
> @hartwork I know how to fix quickly your shader issue, add the `compatibility` keyword after the version number like this:
> 
> ```
> \n	#version 330 compatibility\
> ```

@BenPyton awesome, it works! Pushed as a new commit.


> Because `gl_TexCoord` and other hard coded in/out of GLSL has been deprecated since a long time. Later I should update the fragment shader for a more modern GLSL.

Sounds great!

**Comment by BenPyton** [comment]
Okay, after a lot of trial and errors, I managed to compile on Windows with CMake and VS Code.
Your code changes works as expected on Windows too 🎉 

I have one last question about the github actions: will it run a build when we push or PR too?
I don't know how it works but I see that `push:` and `pull_request:` have nothing after their colons...

**Comment by hartwork** [comment]
> Okay, after a lot of trial and errors, I managed to compile on Windows with CMake and VS Code. Your code changes works as expected on Windows too :tada:

@BenPyton cool!


> I have one last question about the github actions: will it run a build when we push or PR too?

Yes it will! For pull request from a fork there will be an approve button on the pull request page to run the CI, but that's only for when a user contributes the first time, it's for security with secrets in mind in general (but we don't have any here yet). Besides that gate and the button it will run, yes, automatically, every time.

> I don't know how it works but I see that `push:` and `pull_request:` have nothing after their colons...

Good question, let me explain. So the ["normal version"](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-multiple-events) is…
```yaml
on: [push, pull_request]
```

…which is alternative sequence syntax for (and identical to)…

```yaml
on:
- push
- pull_request
```

The reason we have…
```yaml
on:
  push:
  pull_request:
```
…here (which is not a sequence but a mapping in YAML terminology with empty values that are interpreted as `null`) is because only then we can be more specific about details (like affected branches) which we need for a `cron` entry to specify the execution time pattern. For `push` and `pull_request` however defaults — empty — work fine, at least they have for me, I have this working well at multiple other places including e.g. https://github.com/libexpat/libexpat/blob/0a69634eb45e4c169f9c85b03954f26eca61f49b/.github/workflows/linux.yml#L32-L36 .
What do you think?

**Comment by BenPyton** [comment]
Okay, looks fine to me 😄
I merge and we'll see how it goes!

**Comment by hartwork** [comment]
@BenPyton it doesn't show any runs at https://github.com/BenPyton/OsciView/actions yet. Let's give it a minute.

**Comment by hartwork** [comment]
@BenPyton we can use one of the planned follow-up pull requests to trigger a build explicity. What did we have again — inclusion guard names and `find_package` — anything else? What naming pattern would you like to see for the header names?

**Comment by BenPyton** [comment]
@hartwork I have a commit removing the `src/x64/` temporary build folder I missed.
I push it to see if actions are working.

**Comment by hartwork** [comment]
@BenPyton there it is: https://github.com/BenPyton/OsciView/actions :tada:

**Comment by hartwork** [comment]
@BenPyton when you open a pull request now, I'd expect that 5 of the 10 jobs are already green because of the same SHA1 and the `push` part having run already.

**Comment by hartwork** [comment]
@BenPyton you already pushed to `master`, okay. Let's make sure to not duplicate work on `find_package` and the guard renames. Which of these would you like me to take over?

**Comment by BenPyton** [comment]
You can take both, I have another commit to do with the third party lib for FFT.
I will add a submodule and after you made the `find_package` I will try to update the `CMakeList.txt` accordingly.

**Comment by hartwork** [comment]
@BenPyton here you go: #3 and #4

**Pull request merged**
